### ISSUE TITLE
Name can't be set via programmatic configuration

### ISSUE THREAD

**Issue by niggoo** [hazelcast/hazelcast-eureka#19] opened 2018-09-16 04:42 UTC
Hello everyone!

I'm trying to use hazelcast-eureka-one and hazelcast only programmatically, since I'm using Spring for my DI with the hazelcast-spring.jar, it's enough to configure the appropriate Config Bean and Spring would create a hazelcast instance for me. But whatever I do, I can't seem to get the name of the eureka client instance right.

My setup is: Maven Dependencies
```xml
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
            <version>2.0.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.9.3</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-spring</artifactId>
            <version>3.9.3</version>
        </dependency>
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-eureka-one</artifactId>
            <version>1.0.2</version>
        </dependency>
    </dependencies>
```

With the following Config Bean configuration:

```kotlin
@Configuration
class CacheConfiguration {
    @Bean
    fun configuration(
            @Value("\${eureka.client.serviceUrl.defaultZone:http://127.0.0.1:8761/eureka/}") eurekaServiceUrl: String): Config {
        val config = Config()
        val mapConfig = MapConfig("priorities")
                .setTimeToLiveSeconds(10 * 60)
                .setEvictionPolicy(EvictionPolicy.LRU)
                .setMaxSizeConfig(MaxSizeConfig(10, MaxSizeConfig.MaxSizePolicy.FREE_HEAP_SIZE))
        config.addMapConfig(mapConfig)

        val networkConfig = NetworkConfig()
        val joinConfig = JoinConfig()
        val awsConfig = AwsConfig()
        awsConfig.isEnabled = false
        joinConfig.awsConfig = awsConfig
        val tcpIpConfig = TcpIpConfig()
        tcpIpConfig.isEnabled = false
        joinConfig.tcpIpConfig = tcpIpConfig
        val multicastConfig = MulticastConfig()
        multicastConfig.isEnabled = false
        joinConfig.multicastConfig = multicastConfig

        val eurekaDiscoveryConfig = DiscoveryConfig()
        val eurekaDiscoveryStrategyConfig = DiscoveryStrategyConfig(com.hazelcast.eureka.one.EurekaOneDiscoveryStrategyFactory(),
                mapOf(
                        "use-classpath-eureka-client-props" to false,
                        "shouldUseDns" to false,
                        "name" to "hazelcast-cache-cluster",
                        "serviceUrl.default" to eurekaServiceUrl
                ) as Map<String, Comparable<Any?>>?)
        eurekaDiscoveryConfig.discoveryStrategyConfigs.add(eurekaDiscoveryStrategyConfig)
        
        joinConfig.discoveryConfig = eurekaDiscoveryConfig
        networkConfig.join = joinConfig
        config.networkConfig = networkConfig

        config.setProperty("hazelcast.discovery.enabled", "true")

        return config
    }
}
```

So this setup basically works fine, its just that the name of the eureka instance is always UNKNOWN.
When i have eureka-client.properties in place, it just works as expected and the name of the eureka client instance is set correctly.

```properties
hazelcast.shouldUseDns=false
hazelcast.name=hazelcast-cache-cluster
hazelcast.serviceUrl.default=http://127.0.0.1:8761/eureka/
```

Now i debugged through this a little, and the cause seems to be that the name property gets filtered out as to when it gets passed down to the discovery strategy, and I also now know that the file based approach works cause when `MyDataCenterInstanceConfig` is instantiated, it passes the namespace to the `PropertiesInstanceConfig` which in turn uses the `Archaius1Utils.initConfig(CommonConstants.CONFIG_FILE_NAME)` method call to search for the properties file "eureka-client" on the classpath and read the data.

The problem for me now is that I would also like to set a name programmatically, but I really have no clue on how this should be fixed, or even if it is supposed to be this way?

Anyways, thanks for any help in advance!

**Comment by googlielmo** [comment] 2018-09-17 10:14
Hi @niggoo 
Thank you for reporting this and especially for the additional information!
Looks like a defect. We'll take a look.

**Comment by OlegKuts** [comment] 2019-02-13 12:38
Hello. Not sure if this is good place to write about my issue. I am using `hazelcast-eureka plugin`. I get exception when trying to provide properties to DiscoveryStrategyConfig programaticaly using java config like this:
```
                final Config config = new Config();
		config.setInstanceName(instanceName);
		config.setProperty("hazelcast.discovery.enabled", Boolean.TRUE.toString());

		final DiscoveryStrategyConfig strategyConfig = new DiscoveryStrategyConfig(new EurekaOneDiscoveryStrategyFactory());
		strategyConfig.addProperty("use-classpath-eureka-client-props", false);
               //more props here
		final JoinConfig join = config.getNetworkConfig().getJoin();
		join.getMulticastConfig().setEnabled(false);
		join.getDiscoveryConfig().addDiscoveryStrategyConfig(strategyConfig);
		return config;
```
Exception:

> Caused by: java.lang.IllegalStateException: ConfigurationManager is already initialized with configuration org.apache.commons.configuration.MapConfiguration@4c78e00c

Line `strategyConfig.addProperty("use-classpath-eureka-client-props", false);` causes it. 

I am using `hazelcast-eureka-one 1.0.2` and `hazelcast:3.7.8`. It works correct when I am using `eureka-client.properties` file.

Is there any way to configure eureka plugin programmatically?

Full trace:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastInstance' defined in class path resource [com/rbc/gam/head2head/config/HazelcastConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to configure discovery strategies
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1178)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.rbc.gam.head2head.Head2headApplication.main(Head2headApplication.java:18)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcastInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to configure discovery strategies
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 20 common frames omitted
Caused by: java.lang.RuntimeException: Failed to configure discovery strategies
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:168)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
	at com.hazelcast.instance.Node.createDiscoveryService(Node.java:226)
	at com.hazelcast.instance.Node.<init>(Node.java:193)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:153)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.rbc.gam.head2head.config.HazelcastConfig.hazelcastInstance(HazelcastConfig.java:51)
	at com.rbc.gam.head2head.config.HazelcastConfig$$EnhancerBySpringCGLIB$$d1406f60.CGLIB$hazelcastInstance$1(<generated>)
	at com.rbc.gam.head2head.config.HazelcastConfig$$EnhancerBySpringCGLIB$$d1406f60$$FastClassBySpringCGLIB$$c125b230.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.rbc.gam.head2head.config.HazelcastConfig$$EnhancerBySpringCGLIB$$d1406f60.hazelcastInstance(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 21 common frames omitted
Caused by: java.lang.IllegalStateException: ConfigurationManager is already initialized with configuration org.apache.commons.configuration.MapConfiguration@4c78e00c
	at com.netflix.config.DynamicPropertyFactory.initWithConfigurationSource(DynamicPropertyFactory.java:146)
	at com.hazelcast.eureka.one.PropertyBasedEurekaClientConfig.<init>(PropertyBasedEurekaClientConfig.java:57)
	at com.hazelcast.eureka.one.EurekaOneDiscoveryStrategy.<init>(EurekaOneDiscoveryStrategy.java:179)
	at com.hazelcast.eureka.one.EurekaOneDiscoveryStrategy.<init>(EurekaOneDiscoveryStrategy.java:63)
	at com.hazelcast.eureka.one.EurekaOneDiscoveryStrategy$EurekaOneDiscoveryStrategyBuilder.build(EurekaOneDiscoveryStrategy.java:125)
	at com.hazelcast.eureka.one.EurekaOneDiscoveryStrategyFactory.newDiscoveryStrategy(EurekaOneDiscoveryStrategyFactory.java:57)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:217)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:158)
	... 42 common frames omitted

**Comment by OlegKuts** [comment] 2019-02-13 13:11
Any update on this bug? Facing it too for `hazelcast versions 3.9-3.11.1` and `hazelcast-eureka-one 1.0.2 - 1.1`. When using lower hazelcast vesrion - it does not let me set properties programmatically  from Java code. 
For `hazelcast 3.11.1` I get next exception:

> Caused by: com.hazelcast.config.InvalidConfigurationException: Unknown properties: '[name]' on discovery strategy

**Comment by googlielmo** [comment] 2019-02-13 14:34
Hi @OlegKuts 
Looks like what @y986873c mentioned – only two properties were reserved – was already fixed in 1.0.2.
In the current release only the original issue about the `name` still remains to be fixed. It's next on our list, so stay tuned.

**Closed** 2019-03-05 08:30 UTC
Labels: bug

**Comment by OlegKuts** [comment] 2019-03-21 19:52
Good news. This fix will be available in new `hazelcast-eureka-one`  release?

**Comment by mesutcelik** [comment] 2019-03-21 20:48
yes. It is available in 1.1.1 release. please see the [release notes](https://github.com/hazelcast/hazelcast-eureka/releases/tag/v1.1.1)

**Comment by OlegKuts** [comment] 2019-03-22 14:21
@mesutcelik  hey, thanks for quick reply. Is `1.1.1` available in maven repository? Was not able to find it there, nor update my current version in project.

**Comment by mesutcelik** [comment] 2019-03-22 14:24
I see.
@googlielmo ?

**Comment by googlielmo** [comment] 2019-03-25 15:36
@OlegKuts thanks for reporting! We had issue during publishing to central, should be okay now.
