### ISSUE TITLE
Metadata example doesn't seem to work with different app names

### ISSUE THREAD

**Issue by KramKroc** [hazelcast/hazelcast-eureka#33] opened 2019-06-06 11:00 UTC
I've created a fork of the samples project which can be found here:

https://github.com/KramKroc/hazelcast-code-samples/tree/master/hazelcast-integration/eureka/springboot-embedded

My issue is that our production code shares a cluster across two separate spring applications, while all the sample code is based on same application creating the cluster. 

I've updated the separate-client code to use the same hazelcast name and that works correctly to create the cluster which can be verified using:

```
$ java -jar hazelcast-separate-client/target/hazelcast-separate-client-0.1-SNAPSHOT.jar --server.port=8080 --hazelcast.port=5701 --spring.application.name=app1

$ java -jar hazelcast-separate-client/target/hazelcast-separate-client-0.1-SNAPSHOT.jar --server.port=8081 --hazelcast.port=5703 --spring.application.name=app2
```

When I tried similar changes with the metadata project, I just cannot get the cluster to be created so I wondered if there's a bug there:

```
$ java -jar hazelcast-metadata/target/hazelcast-metadata-0.1-SNAPSHOT.jar --server.port=8080 --hazelcast.port=5701 --spring.application.name=app1

$ java -jar hazelcast-metadata/target/hazelcast-metadata-0.1-SNAPSHOT.jar --server.port=8081 --hazelcast.port=5703 --spring.application.name=app2
```

You can see the config I'm using here:

https://github.com/KramKroc/hazelcast-code-samples/blob/master/hazelcast-integration/eureka/springboot-embedded/hazelcast-metadata/src/main/java/com/hazelcast/samples/eureka/Application.java

```java
    @Bean
    public Config hazelcastConfig(EurekaClient eurekaClient) {
        EurekaOneDiscoveryStrategyFactory.setEurekaClient(eurekaClient);
        Config config = new Config();
        config.getNetworkConfig().setPort(hazelcastPort);
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getEurekaConfig()
              .setEnabled(true)
              .setProperty("self-registration", "true")
              .setProperty("use-classpath-eureka-client-props", "false")
              .setProperty("namespace", "hazelcast")
              .setProperty("name", "blag")
              .setProperty("shouldUseDns", "false")              
              .setProperty("serviceUrl.default", "http://localhost:8761/eureka/")              
              .setProperty("use-metadata-for-host-and-port", "true");
        return config;
    }
```

**Comment by googlielmo** [comment] 2019-06-06 16:12
Hi @KramKroc 

At a glance, it seems you would like both clients to use the same metadata for the Hazelcast cluster regardless of the Eureka app name they register with.

I don't think it's possible, and that is by design: i.e., if you use metadata to store cluster member addresses on eureka app "hazelcast" then the discovery plugin will only find the addresses stored in the metadata for "hazelcast", not for any other app.

If this is the case, using separate Eureka clients pointing to the same Eureka app (e.g., "hazelcast") is the way to go.

Cheers,
Guglielmo

**Comment by KramKroc** [comment] 2019-06-07 13:02
Thanks for the reply @googlielmo and that makes sense, I just wanted to confirm that was the case. Worth a note in the markdown to example that scenario?

**Comment by googlielmo** [comment] 2019-06-07 13:13
Good point, thanks @KramKroc!
I just updated the README. I'm going to close this issue then.

Cheers,
Guglielmo

**Closed by googlielmo** 2019-06-07 13:13 UTC
